# Generated by Django 3.2.5 on 2023-08-09 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/')),
                ('alt_text', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 288732, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 287744, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 287744, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 288732, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 288732, tzinfo=utc))),
                ('available_for_sale', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('image_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.image')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 288732, tzinfo=utc))),
                ('product_collection', models.ManyToManyField(to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 300727, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 36, 33, 300727, tzinfo=utc))),
                ('product_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categories')),
            ],
        ),
    ]
