# Generated by Django 3.2.5 on 2023-08-09 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20230809_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 714846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 714846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 702849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 701842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 700843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 700843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 701842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='variant',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 6, 4, 701842, tzinfo=utc)),
        ),
    ]
