# Generated by Django 3.2.5 on 2023-08-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_categories_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categories'),
        ),
    ]
