# Generated by Django 3.2.5 on 2023-08-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_categories_subcategory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['id'], name='ecommerce_c_id_ae430e_idx'),
        ),
    ]
