# Generated by Django 3.2.5 on 2023-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_collection_ecommerce_c_id_ae430e_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['id'], name='ecommerce_c_id_ac3e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['id'], name='ecommerce_v_id_d6b04b_idx'),
        ),
    ]
