# Generated by Django 3.2.5 on 2023-08-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20230810_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.categories'),
        ),
    ]
