# Generated by Django 3.2.5 on 2023-08-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_alter_categories_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='subcategory',
            new_name='parent',
        ),
    ]
