# Generated by Django 3.2.5 on 2023-08-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_rename_subcategory_categories_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='ecommerce_c_id_ac3e7d_idx',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='product_collection',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product_image',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='image_variant',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='product_variant',
            new_name='product',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id'], name='ecommerce_c_id_6efa2c_idx'),
        ),
    ]
