# Generated by Django 3.2.5 on 2023-08-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20230810_1544'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='ecommerce_c_id_6efa2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='ecommerce_c_id_ae430e_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='ecommerce_v_id_d6b04b_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.image'),
        ),
    ]
